name: Static Site CI/CD

on: 
    push:
        branches-ignore: [prod]
    pull_request:
        branches: [int, staging, prod]
    release:
        branches: [prod]
        types: [published]
jobs:

    build:
        name: Test/Build
        runs-on: ubuntu-latest
        env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            HUSKY_SKIP_INSTALL: 1
        container:
            image: 'node:14-alpine'
        steps:
            - name: Set environment vars
              run: |
                if [ $GITHUB_EVENT_NAME == "release" ] || [ "${GITHUB_REF#refs/*/}" == "staging" ]; then
                    echo "::set-env name=NODE_ENV::${GITHUB_REF#refs/*/}"
                else
                    echo "::set-env name=NODE_ENV::int"
                fi

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm ci --unsafe-perm

            - name: Run tests
              run: npm run test

            - name: Build app
              run: npm run build

            - name: Upload app artifacts
              if: github.event_name != 'pull_request'
              uses: actions/upload-artifact@master
              with:
                name: dist
                path: ./build

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: build
        if: github.event_name != 'pull_request'
        steps:
            - name: Set environment vars
              id: vars
              run: |
                if [ $GITHUB_EVENT_NAME == "release" ]; then
                    echo "::set-output name=domain::admin.uriux-test.com"
                else
                    echo "::set-output name=domain::admin.$(echo ${GITHUB_REF#refs/*/} | sed -e 's/\//-/g').uriux-test.com"
                fi

            - name: Download app artifacts
              uses: actions/download-artifact@master
              with:
                name: dist
                path: ./dist

            - name: Deploy to AWS
              uses: onramper/action-deploy-aws-static-site@v1
              env:
                CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_TEST_ACCOUNT }}
              with:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                domain: ${{ steps.vars.outputs.domain }}
                publish_dir: ./dist
